# Generated by Django 5.2.4 on 2025-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userloginhistory_companyloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='num_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='num_managers',
            field=models.IntegerField(default=0),
        ),
    ]
