# Generated by Django 5.2.4 on 2025-07-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_company_num_employees_company_num_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
