# Generated by Django 5.2.4 on 2025-07-13 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_shift_end_employee_shift_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expected_entry_time', models.TimeField(blank=True, null=True)),
                ('expected_exit_time', models.TimeField(blank=True, null=True)),
                ('real_entry_time', models.TimeField(blank=True, null=True)),
                ('real_exit_time', models.TimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.manager')),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
                'unique_together': {('company', 'user_email', 'date')},
            },
        ),
    ]
