# Generated by Django 5.2.4 on 2025-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
