# Generated by Django 5.2.4 on 2025-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_managers',
            field=models.ManyToManyField(blank=True, to='myapp.manager'),
        ),
    ]
