# Generated by Django 5.2.4 on 2025-08-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_taskassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_employees',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_managers',
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
