# Generated by Django 5.2.4 on 2025-08-12 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_task_assigned_employees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed_by_user', models.BooleanField(default=False)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.manager')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='employee_tasks', through='myapp.TaskAssignment', to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_managers',
            field=models.ManyToManyField(blank=True, related_name='manager_tasks', through='myapp.TaskAssignment', to='myapp.manager'),
        ),
    ]
