# Generated by Django 5.2.4 on 2025-08-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_taskassignment_task_assigned_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
            preserve_default=False,
        ),
    ]
